version: '3'
services:
  app:
    build: .
    ports:
      - ${PORT}:8080
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - BASE_URL=${BASE_URL}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - PUBLIC_KEY=${PUBLIC_KEY}
    volumes:
      - ${LOG_DIR}:/app/logs
